kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: namespace-name 
  name: user-grants
rules:
  - apiGroups: ["*"]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "" to read pods in the "default" namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: namespace-name
subjects:
- kind: User
  name: username # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: user-grants # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
