apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-name
  namespace: namespace-name
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: namespace-name
  name: sa-name
rules:
  - apiGroups: ["*"]
    resources: ["pods", "pods/log", "cm" ]
    verbs: ["get", "watch", "list", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "create", "delete", "update", "patch"]
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["create", "update", "delete", "get", "list", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-name
  namespace: namespace-name
subjects:
  - kind: ServiceAccount
    name: sa-name
    namespace: namespace-name
roleRef:
  kind: Role
  name: sa-name
  apiGroup: rbac.authorization.k8s.io
